Misc updates (#160)
* changes to #115

* testing out adding modeling pacakges to suggests

* first attempt at getting around CXX14 travis issues

* second attempt at getting around CXX14 travis issues

* third attempt at getting around CXX14 travis issues (xenial)

* fourth attempt at getting around CXX14 travis issues

* fifth attempt at getting around CXX14 travis issues

* sizth attempt at getting around CXX14 travis issues

* abandoning rstanarm on travis

* cleaned the travis house to see what runs and fails

* no rstanarm and back to trusty

* trying to avoid travis failures for devtools

```
* installing *source* package ‘devtools’ ...
** package ‘devtools’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called ‘magrittr’
ERROR: lazy loading failed for package ‘devtools’
* removing ‘/home/travis/R/Library/devtools’
* restoring previous ‘/home/travis/R/Library/devtools’
The downloaded source packages are in
	‘/tmp/RtmpUhu1j4/downloaded_packages’
Warning message:
In install.packages(c("devtools")) :
  installation of package ‘devtools’ had non-zero exit status
```

* back to original travis file

* reformatting

* R-devel complains about calling by namespace without loading

* seventh attempt at getting around CXX14 travis issues

* eigth attempt at getting around CXX14 travis issues

* bad backtick!

* moved makevars stuff to before_install

* adding C50 and rstanarm back into travis builds

* get binaries for stan packages

* CXX14FLAGS for rstan

* more binaries

* no stan

* no stan (I mean it this time)

* one last library call

* fixed test case

* more changes for r-devel

* removed specific top-level stan calls

* remove ancillary files

* avodi returning multiple logicals

* back to computing probability results

* added library calls

* namespace the predict function