prevent error when getting predicted probabilities from logistic regression when Y is numeric (0,1) or logical
> Error: Columns 1, 2 must be named.
> Use .name_repair to specify repair.