changes for issues #120 and #115 (#159)
For classification problems, an error is thrown if the outcome is not a factor: 

```
Error: For classification models, the outcome should be a factor.
```

There are a lot of travis related changes too: 

  * To get travis to run tests, the modeling packages have to be formal dependencies so a bunch were added to Suggests. This _may_ be temporary; I may decide to remove these for the version sent to CRAN. `rstanarm` was excluded because compiling it (and its dependencies) exceeded the time allowed by travis. 

 * A variety of changes were made to the tests related to r-devel. It looks like any function directly accessed in the tests now need to be formal dependencies (not the case before). There is still some weirdness about this though and I've attributed it to being _devel_. Hopefully this will get smoothed out.